grupo10/api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register(r'Products', views.ProductViewSet, basename='product')

urlpatterns = [
   path('', include(router.urls)),
   path('api-auth/', include('rest_framework.urls'), name='rest_framework'),
]

grupo10/grupo10/urls.py
from django.contrib import admin
from django.urls import path, include
from web import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),    
    path('api', include('api.urls'))
]

grupo10/web/models.py
from django.db import models
from grupo10 import settings

class Client(models.Model):
    email = models.EmailField(max_length=100, verbose_name="Email")
    phone = models.CharField(max_length=100, verbose_name="Teléfono")
    dni = models.CharField(max_length=100, verbose_name="DNI")
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name} | dni:{self.dni}"

class Product(models.Model):
    class CategoryChoices(models.TextChoices):
        MAIN = 'MAIN', 'Principal'
        SIDE = 'SIDE', 'Acompañamiento'
        DESSERT = 'DESRT', 'Postre'
        SALAD = 'SALAD', 'Ensalada'
        DRINK = 'DRINK', 'Bebida'

    name = models.CharField(max_length=100, verbose_name="Nombre")
    price = models.FloatField(max_length=100, verbose_name="Precio")
    category = models.CharField(
        max_length=5,
        choices=CategoryChoices.choices,
        verbose_name="Categoría"
    )
    description = models.CharField(max_length=100, verbose_name="Descripción")

    def __str__(self):
        return f"{self.name} price:{self.price} category:{self.category}"
    
class Order(models.Model):
    date = models.DateField(verbose_name="Fecha", auto_now_add=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name="Cliente")
    products = models.ManyToManyField(Product, verbose_name="Productos")

    def __str__(self):
        return f"{self.date} | client:{self.client.user.first_name} {self.client.user.last_name} | productos:{self.products.all()}"

grupo10/web/templates/web/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %} {% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'web/favicon.svg' %}">
    <link rel="stylesheet" href="{% static 'web/style/base.css' %}">

    {% block extra_css %}
    {% endblock %}
</head>

<body>
    <header class="cremita" >
        <nav class="nav cremita">
            <ul class="ulnav cremita">
                <li>
                    <h2>
                    <a href="{% url 'index' %}">Es restó</a>
                    </h2>
                </li>
                <li><a href="{% url 'menu' %}">Menú</a></li>
                {% if not user.is_authenticated %}<li><a href="{% url 'clientForm' %}">Registrate!</a></li>{% endif %}
                {% if user.is_authenticated %}
                <li><a href="{% url 'orderForm' %}">Hacer pedido!</a></li>
                <li><a href="{% url 'orders' %}">Mis pedidos</a></li>
                {% if perms.web.view_client %}<li><a href="{% url 'clients' %}">Lista de <br/> clientes</a></li>{% endif %}
                {% if perms.web.create_product %}<li><a href="{% url 'productForm' %}">Ingresar <br/> producto</a></li>{% endif %}
                {% endif %}
            </ul>

            <div>
                {% if user.is_authenticated %}<div class="user" >Hola, {{ user.username | title }}</div>{% endif %}
                {% if not user.is_authenticated %}<a class="login" href="{% url 'login' %}">Login</a> {% endif %}
                {% if user.is_authenticated %}<a class="logout" href="{% url 'logout' %}">Logout</a> {% endif %}
            </div>
        </nav>
    </header>



    <main class="centered">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{message.tags}}" {% endif %}> {{message}} </li>
            {% endfor %}
        </ul>
        {% endif %}

        {% block main %}{% endblock %}
    </main>

    <footer class="centered cremita">
        © Todos los derechos reservados
    </footer>
</body>

</html>

grupo10/web/templates/web/clientForm.html
{% extends "web/base.html" %}
{% load static %}

{% block titulo %} Registrate {% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'web/style/clientForm.css' %}">
{% endblock %}

{% block main %}
<h3 class="centered">Registrate</h3>
<br />
{% if clientForm.non_field_errors %}
<div class="error">
    {% for error in clientForm.non_field_errors %}
    <p>{{ error }}</p>
    {% endfor %}
</div>
<br />
{% endif %}

<form method="POST" action="{% url 'clientForm' %}">

    {% csrf_token %}
    
        {{ clientForm.username }}
        {% if clientForm.username.errors %}
        <div class="error">
            {% for error in clientForm.username.errors %}
            <p>{{ error }}</p>
            {% endfor %}
        </div>
        {% endif %}

    {{ clientForm.first_name }}
    {% if clientForm.first_name.errors %}
    <div class="error">
        {% for error in clientForm.first_name.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    {% endif %}

    {{ clientForm.last_name }}
    {% if clientForm.last_name.errors %}
    <div class="error">
        {% for error in clientForm.last_name.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    {% endif %}

    {{ clientForm.password }}
    {% if clientForm.password.errors %}
    <div class="error">
        {% for error in clientForm.password.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    {% endif %}

    {{ clientForm.confirm_password }}
    {% if clientForm.confirm_password.errors %}
    <div class="error">
        {% for error in clientForm.confirm_password.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    {% endif %}

    {{ clientForm.phone }}
    {% if clientForm.phone.errors %}
    <div class="error">
        {% for error in clientForm.phone.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    {% endif %}

    {{ clientForm.email }}
    {% if clientForm.email.errors %}
    <div class="error">
        {% for error in clientForm.email.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    {% endif %}

    {{ clientForm.dni }}
    {% if clientForm.dni.errors %}
    <div class="error">
        {% for error in clientForm.dni.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    {% endif %}

    <input class="hover-effect" type="submit" value="Enviar">
</form>
{% endblock %}

grupo10/web/templates/web/clients.html
{% extends "web/base.html" %}
{% load static %}


{% block titulo %} clientes {% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'web/style/clients.css' %}">
{% endblock %}


{% block main %}
<table>
    <tr>
        <th>Usuario</th>
        <th>Nombre y Apellido</th>
        <th>Email</th>
        <th>Teléfono</th>
        <th>DNI</th>
        <th>Rol</th>
    </tr>
    {% for client in clients %}
    <tr>
        <td><b> {{ client.user }}</b></td>
        <td>{{ client.user.first_name | title }} {{ client.user.last_name | title }}</td>
        <td> {{ client.email }}</td>
        <td> {{ client.phone }}</td>
        <td> {{ client.dni }}</td>
        <td>{% if client.user.is_staff %} Admin {% else %} Cliente {% endif %}</td>

    </tr>
    {% empty %}
    <article>
        <p>No hay clientes disponibles</p>
    </article>
    {% endfor %}
</table>
{% endblock %}

grupo10/web/templates/web/index.html
{% extends "web/base.html" %}
{% load static %}


{% block titulo %} home {% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'web/style/index.css' %}">
{% endblock %}

{% block main %}
    <a style="background-color: transparent;" href="{% url 'menu' %}">
        <img src="{% static 'web/img/comida.webp' %}" alt="Hero pic">
    </a>
{% endblock %}

grupo10/web/templates/web/menu.html
{% extends "web/base.html" %}
{% load static %}


{% block titulo %} menú {% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'web/style/menu.css' %}">
{% endblock %}


{% block main %}
<table>
    <tr>
        <th>Producto</th>
        <th>Precio</th>
        <th>Categoría</th>
    </tr>
    {% for product in products %}
    <tr>
        <td>
            <a href="{% url 'productDetail' product.id %}">
                <img src="{{ product.description }}" alt="{{ product.description }}"
                    class="img" style="height: 4rem; border-radius: 2rem; width: 4rem; margin-left: 2rem;">
                {{ product.name | title }}
            </a>
        </td>
        <td>$ {{ product.price|floatformat:2 }}</td>
        <td>{{ product.get_category_display }}</td>      
    </tr>
    {% empty %}
    <article>
        <p>No hay productos disponibles</p>
    </article>
    {% endfor %}
</table>
{% endblock %}

grupo10/web/templates/web/orderForm.html
{% extends "web/base.html" %}
{% load static %}

{% block titulo %}pedido{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'web/style/orderForm.css' %}">
{% endblock %}

{% block main %}
<h1 class="centered">Hacer pedido</h1>
<br />
{% if form.non_field_errors %}
<div class="error">
    {% for error in form.non_field_errors %}
    <p>{{ error }}</p>
    {% endfor %}
</div>
<br />
{% endif %}

<form method="POST" action="{% url 'orderForm' %}">
    {% csrf_token %}
    
    <!-- Renderizamos los productos en una tabla personalizada -->
    <table class="table">
        <tr>
            <th>Seleccionar</th>
            <th>Producto</th>
            <th>Precio</th>
            <!-- <th>Cantidad</th> -->
        </tr>
        {% for product in products %}
        <tr>
            <td style="display: flex; ">
                <input type="checkbox" name="products" value="{{ product.id }}" class="product-checkbox">
                <img src="{{ product.description }}" alt="{{ product.description }}"
                style="height: 3rem; border-radius: 2rem; width: 3rem; margin-left: 2rem;">
            
            </td>
            <td>
                {{ product.name }}
            </td>
            <td class="product-price">{{ product.price|floatformat:2 }}</td>
            <td>
            </td>
            <!-- <td><input type="number" name="quantities_{{ product.id }}" value="1" min="1" class="quantity-input"></td> -->
        </tr>
        {% endfor %}
    </table>

    <h3>Total: $<span id="total-price">0.00</span></h3>
    <br>
    <input class="hover-effect" id="button" type="submit" value="Enviar" style="width: 12rem;cursor: pointer;">
</form>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const checkboxes = document.querySelectorAll('.product-checkbox');
        const quantityInputs = document.querySelectorAll('.quantity-input');
        const totalPriceElement = document.getElementById('total-price');

        function calculateTotal() {
            let total = 0;
            checkboxes.forEach((checkbox, index) => {
                if (checkbox.checked) {
                    const price = parseFloat(document.querySelectorAll('.product-price')[index].textContent);
                    const quantity = 1;
                    // const quantity = parseInt(quantityInputs[index].value);
                    total += price * quantity;
                }
            });
            totalPriceElement.textContent = total.toFixed(2);
        }

        checkboxes.forEach(checkbox => {
            checkbox.addEventListener('change', calculateTotal);
        });

        quantityInputs.forEach(input => {
            input.addEventListener('input', calculateTotal);
        });
    });
</script>
{% endblock %}

grupo10/web/templates/web/orderList.html
{% extends "web/base.html" %}
{% load static %}

{% block titulo %}Menú{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'web/style/orderList.css' %}">
{% endblock %}

{% block main %}

    <table>
        <tr>
            <th>Fecha</th>
            <th>Producto</th>
            <th>Precio</th>
            <th>Total</th>
        </tr>
    {% for order in orders %}
        <tr class="row">
            <td><p>{{ order.date }}</p></td>
            <td>
                {% for product in order.products.all %}
              
                    <div style="text-align: left; flex-grow: 1;">{{ product.name }}</div>
                  
              
                {% endfor %}
            </td>
            <td>
                {% for product in order.products.all %}
              
                  
                    <div style="text-align: right;">$ {{ product.price|floatformat:2 }}</div>
              
                {% endfor %}
            </td>
            <td>
                <p style="text-align: right;">$ {{ order.total_price|floatformat:2 }}</p>
            </td>
        </tr>
    {% empty %}
    <article>
        <p>No hay pedidos realizados</p>
    </article>
    {% endfor %}
    </table>

{% endblock %}

grupo10/web/templates/web/productDelete.html
{% extends "web/base.html" %}
{% load static %}


{% block titulo %} menú {% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'web/style/productEdit.css' %}">
{% endblock %}


{% block main %}

  <h2>Eliminar Producto</h2>
  <br>
  <p>¿Estás seguro que deseas eliminar el producto "{{ product.name }}"?</p>
  <form method="post">
    {% csrf_token %}
    <br>
    <div class="buttons">

      <button type="submit">Sí, eliminar</button>
      
      <a class="cancelar" href="{% url 'index' %}">Cancelar</a>
    </div>
  </form>

{% endblock %}

grupo10/web/templates/web/productDetail.html
{% extends "web/base.html" %}
{% load static %}


{% block titulo %} menú {% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'web/style/productDetail.css' %}">
{% endblock %}


{% block main %}

  <!-- <h3>Detalle del Producto</h3> -->
  <h3>{{ product.name }}</h3>
  <br>
  <img src="{{ product.description }}" alt="{{ product.name }}" class="dropshadow" style="height: 8rem; width: auto; background-color: transparent; filter: drop-shadow(6px 6px 20px);">
  <br>
  <p><strong>Precio:</strong> $ {{ product.price|floatformat:2 }}</p>
  <p><strong>Categoría:</strong> {{ product.get_category_display  }}</p>
  <!-- <p><strong>Descripción:</strong> {{ product.description }}</p> -->
  <br>
  {% if perms.web.user_admin %}
  <div style="display: flex; gap: 0.5em;">

    <a class="buttons" href="{% url 'productEdit' product.id %}">Editar</a>
    <a class="buttons" href="{% url 'productDelete' product.id %}">Borrar</a>
  </div>
  {% endif %}
  <br>
  <br>
  <a class="buttons" href="{% url 'menu' %}">Volver a la lista de productos</a>


{% endblock %}

grupo10/web/templates/web/productEdit.html
{% extends "web/base.html" %}
{% load static %}


{% block titulo %} menú {% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'web/style/productEdit.css' %}">
{% endblock %}


{% block main %}

  <h2>Editar Producto</h2>
  <br>
  <br>
  <form method="post">
    {% csrf_token %}
    {{ productForm.as_p }}
    <button class="hover-effect" type="submit">Guardar Cambios</button>
  </form>
  <br>
  <br>
  <a class="cancelar" href="{% url 'menu' %}">Cancelar</a>

{% endblock %}

grupo10/web/templates/web/productForm.html
{% extends "web/base.html" %}
{% load static %}


{% block titulo %} ingresar producto {% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'web/style/productForm.css' %}">
{% endblock %}

{% block main %}
<h3 class="centered">Ingresar nuevo producto</h3>
<br />
{% if productForm.non_field_errors %}
<div class="error">
    {% for error in productForm.non_field_errors %}
    <p>{{ error }}</p>
    {% endfor %}
</div>
<br />
{% endif %}

<form method="POST" action="{% url 'productForm' %}">

    {% csrf_token %}
    <!-- {{ productForm.as_p }} -->

    {{ productForm.name }}
    {% if productForm.name.errors %}
    <div class="error">
        {% for error in productForm.name.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    {% endif %}

    {{ productForm.price }}
    {% if productForm.price.errors %}
    <div class="error">
        {% for error in productForm.price.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    {% endif %}

    {{ productForm.category }}
    {% if productForm.category.errors %}
    <div class="error">
        {% for error in productForm.category.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    {% endif %}

    {{ productForm.description }}
    {% if productForm.description.errors %}
    <div class="error">
        {% for error in productForm.description.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    {% endif %}

    <input class="hover-effect" type="submit" value="Enviar">
</form>
{% endblock %}